name: one_gym_app
description: "Premium gym management app - MVP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.8.4

  # Firebase / FCM
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.4.1

  # Routing
  go_router: ^14.6.2

  # Utils
  shared_preferences: ^2.3.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true