// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEdxWp_L1_tMAK4jcWyLLOwYdcLwJa2Ds',
    appId: '1:851695716010:web:90171d2105e653b062b2d3',
    messagingSenderId: '851695716010',
    projectId: 'gym-app-dev-9ca32',
    authDomain: 'gym-app-dev-9ca32.firebaseapp.com',
    storageBucket: 'gym-app-dev-9ca32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkDFwzZZgDQTq2qrJEbrpj0PUcIKZx1bc',
    appId: '1:851695716010:android:161aed657e519bc662b2d3',
    messagingSenderId: '851695716010',
    projectId: 'gym-app-dev-9ca32',
    storageBucket: 'gym-app-dev-9ca32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABiWF_nHoUQij5m-zH-jf5JS7bvs_64Pc',
    appId: '1:851695716010:ios:f84010044157460662b2d3',
    messagingSenderId: '851695716010',
    projectId: 'gym-app-dev-9ca32',
    storageBucket: 'gym-app-dev-9ca32.firebasestorage.app',
    iosBundleId: 'com.example.oneGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABiWF_nHoUQij5m-zH-jf5JS7bvs_64Pc',
    appId: '1:851695716010:ios:f84010044157460662b2d3',
    messagingSenderId: '851695716010',
    projectId: 'gym-app-dev-9ca32',
    storageBucket: 'gym-app-dev-9ca32.firebasestorage.app',
    iosBundleId: 'com.example.oneGymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEdxWp_L1_tMAK4jcWyLLOwYdcLwJa2Ds',
    appId: '1:851695716010:web:436cecab350ab54062b2d3',
    messagingSenderId: '851695716010',
    projectId: 'gym-app-dev-9ca32',
    authDomain: 'gym-app-dev-9ca32.firebaseapp.com',
    storageBucket: 'gym-app-dev-9ca32.firebasestorage.app',
  );
}